const STORE = [
    {
        id: 1,
        content: "I saw a rainbow today!",
        public: true,
        user_id: 1,
        date_modified: "2019-07-13 20:39:14",
        tag_amusement: false,
        tag_awe: true,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false
    },
    {
        id: 2,
        content: "There was free shrimp at the buffet.",
        public: true,
        user_id: 1,
        date_modified: "2019-07-23 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: true,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false	
    },
    {
        id: 3,
        content: "Chidi and I kissed under a tree!",
        public: false,
        user_id: 1,
        date_modified: "2019-07-28 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: true,
        tag_pride: false,
        tag_serenity: false	
    },
    {
        id: 4,
        content: "I smelled a beautiful flower today.",
        public: true,
        user_id: 2,
        date_modified: "2019-07-15 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: true	
    },
    {
        id: 5,
        content: "I got Peeps for half off at the store!",
        public: true,
        user_id: 2,
        date_modified: "2019-07-25 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: true,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false,
        tag_other: "thrifty"
    },
    {
        id: 6,
        content: "Eleanor and I kissed under a tree!",
        public: false,
        user_id: 2,
        date_modified: "2019-07-28 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: true,
        tag_pride: false,
        tag_serenity: false	
    },
    {
        id: 7,
        content: "I looked absolutely gorgeous in my Chanel dress at the ball.",
        public: true,
        user_id: 3,
        date_modified: "2019-07-17 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: true,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false	
    },
    {
        id: 8,
        content: "I threw a lovely party that strengthened the neighborhood community.",
        public: true,
        user_id: 3,
        date_modified: "2019-07-27 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: true,
        tag_serenity: false	
    },
    {
        id: 9,
        content: "I have started making amends with my otherwise wretched sister...",
        public: false,
        user_id: 3,
        date_modified: "2019-07-30 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: true,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false	
    },
    {
        id: 10,
        content: "I killed it at the dance competition",
        public: true,
        user_id: 4,
        date_modified: "2019-07-19 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: true,
        tag_serenity: false,
        tag_other: "totally rad"
    },
    {
        id: 11,
        content: "I am in a very entrepreneurial community",
        public: true,
        user_id: 4,
        date_modified: "2019-07-29 20:39:14",
        tag_amusement: false,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: true,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false	
    },
    {
        id: 12,
        content: "I do not know where I am, which is kind of exciting!",
        public: false,
        user_id: 4,
        date_modified: "2019-07-31 20:39:14",
        tag_amusement: true,
        tag_awe: false,
        tag_contentment: false,
        tag_gratitude: false,
        tag_inspiration: false,
        tag_joy: false,
        tag_hope: false,
        tag_love: false,
        tag_pride: false,
        tag_serenity: false	
    },
]